name = "omcode-api"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
LOG_LEVEL = "info"

[observability]
enabled = true
head_sampling_rate = 1
